@startuml

participant Browser as "browser"
participant Hive as "Hive"
participant RegUi as "registrationUi"


Browser -> Hive: Запрос на public/auth/browser/registration
Hive -> Browser: Redirect on reg-ui\n/register?request=rId
Browser -> RegUi:  reg-ui\n/register?request=rId
RegUi -> RegUi:
note right: Получить инфу о риквесте /auth/browser/requests/registration?request=rId\nВ ней будет crf token  список полей формы аутентификации.
RegUi -> Browser: Форма аутентификации с базовой валидацией на js

Browser -> Hive:POST public/auth/browser/methods/password/registration?request=rId
Hive -> Hive: GET identity.schema.json from config path
@enduml